name 'icinga'
maintainer 'The Authors'
maintainer_email 'seththoenen@missouristate.edu'
license 'all_rights'
description 'Installs/Configures icinga'
long_description 'Installs/Configures icinga'
version '0.3.0'
