name 'icinga'
maintainer 'Seth Thoenen'
maintainer_email 'seththoenen@missouristate.edu'
license 'all_rights'
description 'Installs/Configures icinga'
long_description 'Installs/Configures icinga on Ubuntu 14.04 LTS'
version '1.0.2'
